// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxVeR9T9gGdOVmIxZJihcEECdbhqhV9w',
    appId: '1:312954186546:web:555f4d856fcdf9c6a8c52b',
    messagingSenderId: '312954186546',
    projectId: 'chatapp-6503d',
    authDomain: 'chatapp-6503d.firebaseapp.com',
    storageBucket: 'chatapp-6503d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8AsKEfcTldr-NgTyp3900uhr_3P5UaTA',
    appId: '1:312954186546:android:bd16df64c14aa872a8c52b',
    messagingSenderId: '312954186546',
    projectId: 'chatapp-6503d',
    storageBucket: 'chatapp-6503d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCls0S8MHvixpWx0i4sjtVennHqaoBvwo',
    appId: '1:312954186546:ios:b3e28a8b7638bc01a8c52b',
    messagingSenderId: '312954186546',
    projectId: 'chatapp-6503d',
    storageBucket: 'chatapp-6503d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCls0S8MHvixpWx0i4sjtVennHqaoBvwo',
    appId: '1:312954186546:ios:b3e28a8b7638bc01a8c52b',
    messagingSenderId: '312954186546',
    projectId: 'chatapp-6503d',
    storageBucket: 'chatapp-6503d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdxVeR9T9gGdOVmIxZJihcEECdbhqhV9w',
    appId: '1:312954186546:web:a74e4f1b718f0df9a8c52b',
    messagingSenderId: '312954186546',
    projectId: 'chatapp-6503d',
    authDomain: 'chatapp-6503d.firebaseapp.com',
    storageBucket: 'chatapp-6503d.firebasestorage.app',
  );
}
